version: '3.7'

services:
  db:
    image: mysql:8
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=Predprof
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - dbdata:/var/lib/mysql

  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    expose:
      - 8000
    command: sh /entrypoint.sh
    depends_on:
      - db

  redis:
    image: redis:alpine
    expose:
      - "6379"

  celelry:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    command: sh /worker_entrypoint.sh

    depends_on:
      - django_gunicorn
      - db
      - redis
      - nginx

  celelry-beat:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    command: sh /beat_entrypoint.sh

    depends_on:
      - django_gunicorn
      - db
      - redis
      - nginx
    
  telegram:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    command: sh /telegram_entrypoint.sh
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
  dbdata:

