# Generated by Django 3.2.16 on 2023-02-14 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(1, 'Ужасно...'), (2, 'Плохо'), (3, 'Сойдёт'), (4, 'Нравится'), (5, 'Обожаю!')], verbose_name='оценка')),
                ('feedback', models.TextField(blank=True, max_length=5000, null=True, verbose_name='отзыв')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.site', verbose_name='сайт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'default_related_name': 'ratings',
            },
        ),
        migrations.AddConstraint(
            model_name='siterating',
            constraint=models.UniqueConstraint(fields=('site', 'user'), name='site_user_unique'),
        ),
    ]
