# Generated by Django 3.2.16 on 2023-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(default='Без описания', max_length=1000, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/', verbose_name='логотип'),
        ),
    ]
