# Generated by Django 3.2.16 on 2023-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230128_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(default='Без описания', max_length=5000, verbose_name='описание'),
        ),
    ]
