# Generated by Django 3.2.16 on 2023-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_usersite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(max_length=100, verbose_name='url'),
        ),
    ]
