# Generated by Django 4.1.5 on 2023-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('status_code', models.IntegerField()),
                ('ping', models.TimeField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
