# Generated by Django 3.2.16 on 2023-02-16 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150, verbose_name='регион')),
                ('problem', models.TextField(max_length=2000, verbose_name='проблема')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('is_checked', models.BooleanField(default=False, verbose_name='рассмотрено')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.site', verbose_name='сайт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сообщение о проблеме',
                'verbose_name_plural': 'сообщения о проблеме',
            },
        ),
    ]
