# Generated by Django 3.2.16 on 2023-02-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_site_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteQueryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.SmallIntegerField(verbose_name='статус')),
                ('ping', models.SmallIntegerField(verbose_name='задержка мс.')),
                ('note_time', models.DateTimeField(auto_now_add=True, verbose_name='время записи')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.site', verbose_name='сайт')),
            ],
        ),
    ]
