# Generated by Django 3.2.16 on 2023-02-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_site_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(verbose_name='статус код')),
                ('ping', models.IntegerField(verbose_name='задержка запроса в миллисекундах')),
                ('note_time', models.DateTimeField(null=True, verbose_name='время записи')),
                ('id_site', models.ForeignKey(default='norm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.site', verbose_name='id сайта')),
            ],
        ),
    ]
