# Generated by Django 3.2.16 on 2023-02-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitequerynote',
            options={'default_related_name': 'query_notes', 'ordering': ('-note_time',)},
        ),
        migrations.AlterField(
            model_name='sitequerynote',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_notes', to='catalog.site', verbose_name='сайт'),
        ),
    ]
