# Generated by Django 3.2.16 on 2023-02-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFallReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteFallReason', models.TextField(max_length=100, verbose_name='причина падения')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='время записи')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.site', verbose_name='сайт')),
            ],
        ),
    ]
