# Generated by Django 3.2.16 on 2023-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20230215_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitequerynote',
            name='ping',
            field=models.FloatField(null=True, verbose_name='задержка мс.'),
        ),
    ]
