# Generated by Django 3.2.16 on 2023-02-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_sitefallreason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitefallreason',
            old_name='SiteFallReason',
            new_name='reason',
        ),
    ]
