<<<<<<< HEAD
# Generated by Django 3.2.16 on 2023-02-18 07:39
=======
# Generated by Django 3.2.16 on 2023-02-18 09:40
>>>>>>> c24c0eb196a7622f765ad99e29c5ca3c4f03b267

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(default=0, verbose_name='chat_id пользователя'),
        ),
    ]
